apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: restbasic-authorization
  namespace: test-project-istio
spec:
  selector:
    matchLabels:
      app: restbasic
      version: v1
  action: ALLOW
  rules:
    - from:
      - source:
          requestPrincipals: ["testing@secure.istio.io/testing@secure.istio.io"]
      to:
        - operation:
            methods: ["GET"]
            paths: ["*"]
      when:
        - key: request.auth.claims[iss]
          values: ["testing@secure.istio.io"]