apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: restbasic-jwt
  namespace: test-project-istio
spec:
  selector:
    matchLabels:
      app: restbasic
  jwtRules:
    - issuer: "testing@secure.istio.io"
      jwksUri: "https://github.com/giorman/springboot/blob/master/security/jwks.json"