apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: restbasic-authentication
  namespace: test-project-istio
spec:
  selector:
    matchLabels:
      app: restbasic
      version: v1
  jwtRules:
    - issuer: "testing@secure.istio.io"
      jwks: "{ 'keys':[{'e':'AQAB','kid':'V4Z7bWYkiDYBSqxIAnn1b4TApogSRFN6TBQokmNpAGk','kty':'RSA','n':'2jpr1yrg8qSWIHSYSPDFjWxfsM3EyWg2fCbvhdYwfdiWflRWDot0QQIIiCXvBUd7_aLFN9Og8FtXGcq6waJmK7U285PErzjdbtzunQGDGKvYcosaAlVfML49jB8Te7lXEH3l8Dit95fjNcmkkLfKUgdwLDzPztvq0YAlwQ'}]}"

