apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: restbasic-vs
spec:
  hosts:
    - restbasic-test-project-istio.apps.ocpdes.ambientesbc.lab
  gateways:
    - restbasic-gateway
  http:
    - match:
        - uri:
            exact: /hello
      route:
        - destination:
            host: restbasic
            port:
              number: 9090